test:
  key: value1234

redis:
  addr: "localhost:6379"

db:
  src:
    dsn: "root:root@tcp(localhost:3306)/webook"
  dst:
    dsn: "root:root@tcp(localhost:3306)/webook_intr"

kafka:
  addr:
    - "localhost:9094"

grpc:
  server:
    addr: ":8090"

migrator:
  http:
    addr: ":8082"
