test:
  key: 12

redis:
  addr: "localhost:6379"

db:
  dsn: "root:root@tcp(localhost:3306)/webook"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  client:
    intr:
      addr: "localhost:8090"
      threshold: 50
